/**
 * HA mobile_app
 * This is the OpenAPI specification of the mobile_app api of HA
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cbro@semperpax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class WebhookData {
  
  @SerializedName("gps")
  private List<BigDecimal> gps = null;
  @SerializedName("gps_accuracy")
  private Integer gpsAccuracy = null;
  @SerializedName("battery")
  private Integer battery = null;
  @SerializedName("speed")
  private Integer speed = null;
  @SerializedName("altitude")
  private Integer altitude = null;
  @SerializedName("course")
  private Integer course = null;
  @SerializedName("vertical_accuracy")
  private Integer verticalAccuracy = null;

  /**
   * GPS position (in lat, lon)
   **/
  @ApiModelProperty(value = "GPS position (in lat, lon)")
  public List<BigDecimal> getGps() {
    return gps;
  }
  public void setGps(List<BigDecimal> gps) {
    this.gps = gps;
  }

  /**
   * GPS accuracy (in meters)
   **/
  @ApiModelProperty(value = "GPS accuracy (in meters)")
  public Integer getGpsAccuracy() {
    return gpsAccuracy;
  }
  public void setGpsAccuracy(Integer gpsAccuracy) {
    this.gpsAccuracy = gpsAccuracy;
  }

  /**
   * Battery level (in %)
   **/
  @ApiModelProperty(value = "Battery level (in %)")
  public Integer getBattery() {
    return battery;
  }
  public void setBattery(Integer battery) {
    this.battery = battery;
  }

  /**
   * Speed (in m/s)
   **/
  @ApiModelProperty(value = "Speed (in m/s)")
  public Integer getSpeed() {
    return speed;
  }
  public void setSpeed(Integer speed) {
    this.speed = speed;
  }

  /**
   * Altitude (in meters)
   **/
  @ApiModelProperty(value = "Altitude (in meters)")
  public Integer getAltitude() {
    return altitude;
  }
  public void setAltitude(Integer altitude) {
    this.altitude = altitude;
  }

  /**
   * Bearing (in degrees)
   **/
  @ApiModelProperty(value = "Bearing (in degrees)")
  public Integer getCourse() {
    return course;
  }
  public void setCourse(Integer course) {
    this.course = course;
  }

  /**
   * Vertical accuracy (in meters)
   **/
  @ApiModelProperty(value = "Vertical accuracy (in meters)")
  public Integer getVerticalAccuracy() {
    return verticalAccuracy;
  }
  public void setVerticalAccuracy(Integer verticalAccuracy) {
    this.verticalAccuracy = verticalAccuracy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookData webhookData = (WebhookData) o;
    return (this.gps == null ? webhookData.gps == null : this.gps.equals(webhookData.gps)) &&
        (this.gpsAccuracy == null ? webhookData.gpsAccuracy == null : this.gpsAccuracy.equals(webhookData.gpsAccuracy)) &&
        (this.battery == null ? webhookData.battery == null : this.battery.equals(webhookData.battery)) &&
        (this.speed == null ? webhookData.speed == null : this.speed.equals(webhookData.speed)) &&
        (this.altitude == null ? webhookData.altitude == null : this.altitude.equals(webhookData.altitude)) &&
        (this.course == null ? webhookData.course == null : this.course.equals(webhookData.course)) &&
        (this.verticalAccuracy == null ? webhookData.verticalAccuracy == null : this.verticalAccuracy.equals(webhookData.verticalAccuracy));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.gps == null ? 0: this.gps.hashCode());
    result = 31 * result + (this.gpsAccuracy == null ? 0: this.gpsAccuracy.hashCode());
    result = 31 * result + (this.battery == null ? 0: this.battery.hashCode());
    result = 31 * result + (this.speed == null ? 0: this.speed.hashCode());
    result = 31 * result + (this.altitude == null ? 0: this.altitude.hashCode());
    result = 31 * result + (this.course == null ? 0: this.course.hashCode());
    result = 31 * result + (this.verticalAccuracy == null ? 0: this.verticalAccuracy.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookData {\n");
    
    sb.append("  gps: ").append(gps).append("\n");
    sb.append("  gpsAccuracy: ").append(gpsAccuracy).append("\n");
    sb.append("  battery: ").append(battery).append("\n");
    sb.append("  speed: ").append(speed).append("\n");
    sb.append("  altitude: ").append(altitude).append("\n");
    sb.append("  course: ").append(course).append("\n");
    sb.append("  verticalAccuracy: ").append(verticalAccuracy).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
